name: Repository Maintenance

on:
  workflow_dispatch:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  maintenance:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@main
      with:
        ref: test
        fetch-depth: 0
        
    - name: Garbage Collection
      run: |
        git gc --aggressive --prune=now

    - name: Repack Repository
      run: |
        git repack -a -d --depth=250 --window=250

    - name: Verify Repository Integrity
      run: |
        git fsck --full
        
    - name: Setup
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git commit -am "Repo Maintenance Update"
        
    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: test
        force_with_lease: true
      
        
